#+title: Parsex-Cl
#+subtitle: Experimental project for regular expressions, lexer and parser design

* Purpose of this Project
I started this project as an exercise to practice Common Lisp. It is not meant by any means to compete with the well-established, feature-rich *[[https://github.com/edicl/cl-ppcre][CL-PPCRE]]*. However, as this one gets more mature, it could become a component of a bigger idea.


* Status
While it's still at an early experimental condition, it is already capable of matching strings against classical *regular expressions*, that are provided in the form of *s-expressions*. See section entitled [[unit-tests][Unit Tests]] for information about how to experiment with the regex matcher.

* Features

** Regex Format
I'm convinced that in Lisp, there is little reason to use a non-lisp syntax to define regular expressions, for different reasons:

- I get regex parsing almost for free, thanks to the *Common Lisp Reader*. This also allows adding more features in the future, without the need for complicated parser updates.
- Ambiguity related to order of evalution is avoided, thanks to the parentheses.


** Supported Constructs
Regex constructs are either simple (that is, matching a single character), or composed of other constructs.

The following table describes the supported constructs. For brievity, I'm assuming that the reader is already familiar with regular expressions in general.

|-----------------+---------------------------------------------------------------------------------+--------------------------------|
| Regex Element   | Description                                                                     | Example                        |
|-----------------+---------------------------------------------------------------------------------+--------------------------------|
| Character       | Individual characters                                                           | #\a                            |
| Any Character   | An element matching any single character                                        | :any-char                      |
| Character Range | Character range, based on char-code order                                       | (char-range #\A #\F)           |
| Sequence        | Sequence of one or more elements                                                | (seq #\x #\y)                  |
| String          | Sequence of characters                                                          | "xy" (same as previous one)    |
| Choice          | Choice between multiple elements                                                | (or "Hello" "Hi")              |
| Zero or More    | Zero or more occurrences of a specific element (Kleene closure)                 | (* "a")                        |
| One or more     | One or more occurrences of a specific element                                   | (seq "Hell" (+ #\o) #\!)       |
| Zero or One     | Zero or one occurrence of a specific element                                    | (? (or "Mr." "Mrs."))          |
| Regex Negation  | Matches anything other than the specified regex element                         | (not "abc")                    |
| Regex Inversion | Equivalent to the caret (^) inside square brackets in conventional regex format | (inv #\a (char-range #\d #\m)) |
|-----------------+---------------------------------------------------------------------------------+--------------------------------|

Note in the previous table that single character and string elements are specified as they would be read by the Common Lisp *reader*. Construct types (*seq*, *or*, etc.) are specified using symbols.

Note that the *negation* and *inversion* are subject to change. The negation specifically is experimental and tricky (you may not expect the behavior), so it might not be very useful. I may consider merging the negation and inversion into a single construct, with the actual behavior specified by flags.


** Some Implementation Notes

Here are some assorted implementation details, which need to be addressed by expanding them into architecture document, or that may need to be handled in the code (besides being documented):

*** Backtracking
Backtracking in case of no match and in case of /candidate match/ are both implemented in the input source. These features are transparent to the regex matching function itself. There are two benefits from this:

1. The contract between the matching function and the input handling is simple.
2. Different behavior can be implemented in different implementations of the input source, without altering the matching function. For example, more efficient source could be implemented for exact matches only.


* Prerequisites
- Git
- A Common Lisp installation, including ASDF (e.g. SBCL).
- Quicklisp


* Installation

Once the Git repository is cloned, the *ASDF* file (=parsex-cl.asd=) can be compiled and loaded in a REPL session (e.g. Emacs *Slime* REPL).

The project can then be loaded using *Quicklisp*, as follows:

#+begin_src lisp
(ql:quickload 'parsex-cl)  
#+end_src

The project components will be loaded sequentially, as indicated in the following output:

#+begin_example
To load "parsex-cl":
  Load 1 ASDF system:
    parsex-cl
; Loading "parsex-cl"
[package parsex-cl]...............................
[package parsex-cl.tokenizer-states]..............
[package parsex-cl.tokenizer-transitions].........
[package parsex-cl.tokenizer].....................
[package parsex-cl.basic-string-tokenizer]........
[package parsex-cl.common-transition-finders].....
[package parsex-cl.common-atom-matchers]..........
[package parsex-cl.regex].........................
[package parsex-cl.fsm-traversal].................
[package parsex-cl]...............................
[package parsex-cl.graphviz-util].................
[package parsex-cl.test]..........................
[package parsex-cl.tokenizer.test]................
[package parsex-cl.regex.test]..
(PARSEX-CL)
#+end_example

TODO: Enhance.

* Usage

** Unit Tests <<unit-tests>>

Running regex unit test cases selectively can be done by first changing into the regex unit tests package:

#+begin_src lisp
  (in-package :parsex-cl.test/regex.test)
#+end_src

The output and updated prompt will indicate the *test* package:

#+begin_example
#<PACKAGE "PARSEX-CL.TEST/REGEX.TEST">
TEST>
#+end_example

Then, all defined test cases could be executed as follows:

#+begin_example
TEST> (run! :parsex-cl.regex.test-suite)
#+end_example

The output will provide information about the test cases (controlled by dynamic variables), including the following:
- Text being matched.
- Regular expression being matched against.
- Text consumed by the matching process (updated accumulator).
- GraphViz Dot for the NFA finite state machine diagram.
- GraphViz Dot for the DFA finite state machine diagram.
- Test execution status (success/failure).

Here is a sample output for the execution of one of the test cases:

#+begin_example
...
Running test BASIC2-REGEX-MATCHING-TEST 
Matching the text "abcacdaecccaabeadde" against the regex (+
                                                           (OR (CHAR-RANGE a d)
                                                            (CHAR-RANGE b e)))..

Updated accumulator is abcacdaecccaabeadde

Graphviz for NFA:
digraph {
rankdir = LR;

    0 -> 1 [label="b - e"];
    1 -> 2 [label="ε"];
    2 -> 3 [label="ε"];
    2 -> 4 [label="ε"];
    4 -> 5 [label="b - e"];
    5 -> 6 [label="ε"];
    6 -> 3 [label="ε"];
    6 -> 4 [label="ε"];
    4 -> 7 [label="a - d"];
    7 -> 6 [label="ε"];
    0 -> 8 [label="a - d"];
    8 -> 2 [label="ε"];
}


Graphviz for DFA:
digraph {
rankdir = LR;

    0 -> 1 [label="e - e"];
    1 -> 2 [label="e - e"];
    2 -> 2 [label="e - e"];
    2 -> 3 [label="b - d"];
    3 -> 2 [label="e - e"];
    3 -> 3 [label="b - d"];
    3 -> 4 [label="a - a"];
    4 -> 2 [label="e - e"];
    4 -> 3 [label="b - d"];
    4 -> 4 [label="a - a"];
    2 -> 4 [label="a - a"];
    1 -> 3 [label="b - d"];
    1 -> 4 [label="a - a"];
    0 -> 5 [label="b - d"];
    5 -> 2 [label="e - e"];
    5 -> 3 [label="b - d"];
    5 -> 4 [label="a - a"];
    0 -> 6 [label="a - a"];
    6 -> 2 [label="e - e"];
    6 -> 3 [label="b - d"];
    6 -> 4 [label="a - a"];
}

#+end_example

** Visualizing the GraphViz Dot Diagrams

In order to inspect the NFA or DFA visually, the *dot* utility provided with *Graphviz* may be used to export the Dot output into *SVG*.

*Note*: A Graphviz installation is required for this step.

For example, to visualize the DFA corresponding to the test case described in the previous section ([[unit-tests][Unit Tests]]), the following commands can be used (assuming a Unix/Linux terminal):

- Save the Dot output for the DFA into a text file:

#+begin_example
cat > sample-dfa.dot

digraph {
rankdir = LR;

    0 -> 1 [label="e - e"];
    1 -> 2 [label="e - e"];
    2 -> 2 [label="e - e"];
    2 -> 3 [label="b - d"];
    3 -> 2 [label="e - e"];
    3 -> 3 [label="b - d"];
    3 -> 4 [label="a - a"];
    4 -> 2 [label="e - e"];
    4 -> 3 [label="b - d"];
    4 -> 4 [label="a - a"];
    2 -> 4 [label="a - a"];
    1 -> 3 [label="b - d"];
    1 -> 4 [label="a - a"];
    0 -> 5 [label="b - d"];
    5 -> 2 [label="e - e"];
    5 -> 3 [label="b - d"];
    5 -> 4 [label="a - a"];
    0 -> 6 [label="a - a"];
    6 -> 2 [label="e - e"];
    6 -> 3 [label="b - d"];
    6 -> 4 [label="a - a"];
}
^C
#+end_example

- Export the file as SVG:

#+begin_example
dot -Tsvg -Nfontcolor=red -Nshape=circle sample-dfa.dot > sample-dfa.svg
#+end_example

- View the SVG file in any modern web browser, or any vector graphics tool that supports opening/importing files in SVG format.

#+CAPTION: Sample DFA finite state machine diagram
#+NAME:   fig:dfa-fsm-diagram
[[./images/sample-dfa.svg]]


* TODO

- Complete the implementation of negation.
- may split code into multiple packages.
- There are also some TODOs in the source code (to be added in this section).

* Author
+ John Badie (johnkirollos@gmail.com)

